---
# [en_US] Time intervals configuration
#
# [pt_BR] Configurações de intervalos de tempo
#
time_intervals:
  # [en_US] Time interval for check if there are available heroes to work
  # Default value (in minutes): 10
  #
  # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
  # Valor padrão (em minutos): 10
  send_heroes_for_work: 12

  # [en_US] Time interval to update heroes position in the map,
  # Default value (in minutes): 3
  #
  # [pt_BR] Intervalo de tempo para atualizar a posição dos heróis no mapa
  # Valor padrão (em minutos): 3
  refresh_heroes_positions: 3

  # [en_US] Time interval to check for new maps
  # Default value (in minutes): 5
  #
  # [pt_BR] Intervalo de tempo para verificar por novos mapas
  # Valor padrão (em segundos): 5
  check_for_new_map_button: 5

  # [en_US] Time interval to check for login request
  # Default value (in minutes): 3
  #
  # [pt_BR] Intervalo de tempo para verificar se existe solicitação de login
  # Valor padrão (em minutos): 5
  check_for_login: 5

  # [en_US] Time interval between moviments
  # Default value (in seconds): 1
  #
  # [pt_BR] Intervalo de tempo entre movimentos
  # Valor padrão (em segundos): 1
  interval_between_moviments: 1

# [en_US] How confident the bot needs to be to click the buttons (values from 0 to 1. 0 is the minimum value, 1 is the maximum value)
#
# [pt_BR] O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
#
threshold:
  # [en_US]
  # Default value: 0.7
  #
  # [pt_BR]
  # Valor padrão: 0.7
  default: 0.7

  # [en_US]
  # Default value: 0.8
  #
  # [pt_BR]
  # Valor padrão: 0.8
  commom: 0.8

  # [en_US]
  # Default value: 0.8
  #
  # [pt_BR]
  # Valor padrão: 0.8
  select_wallet_buttons: 0.8

  # [en_US]
  # Default value: 0.9
  #
  # [pt_BR]
  # Valor padrão: 0.9
  go_to_work_btn: 0.9

  # [en_US]
  # Default value: 0.9
  #
  # [pt_BR]
  # Valor padrão: 0.9
  go_to_work_all_btn: 0.8

  # [en_US]
  # Default value: 0.9
  #
  # [pt_BR]
  # Valor padrão: 0.9
  green_bar: 0.9

home:
  enable: False
  # If bot is sending the wrong hero home, make this number bigger.
  # if bot is not sending any hero home make this number smaller.
  hero_threshold: 0.90
  home_button_threshold: 0.95

# [en_US]
# Default value: 60
#
# [pt_BR]
# Valor padrão: 60
scroll_size: 60

# [en_US]
# Default value: 3
#
# [pt_BR]
# Valor padrão: 3
scroll_attemps: 4

# [en_US]
# Default value: true
#
# [pt_BR]
# Valor padrão: true
use_click_and_drag_instead_of_scroll: true

# [en_US]
# Default value: 200
#
# [pt_BR]
# Valor padrão: 200
click_and_drag_amount: 200

# [en_US]
# Default value: green
# Available options:
# all   = select all heroes (regardless of the stamina bar)
# green = select the heroes with green stamina bar (half or full)
# full  = select only the heroes with full stamina bar
#
# [pt_BR]
# Valor padrão: green
# Opções disponíveis:
# all   = seleciona todos os heróis (independente da barra de stamina)
# green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
# full  = seleciona somente os heróis com a barra de stamina cheia
select_heroes_mode: "green"

# [en_US] Option for save logs to a file (logs.txt)
# Default value: False
# Available options: False or True
#
# [pt_BR] Opção para salvar os logs em arquivo (logs.txt)
# Valor padrão : False
# Opções disponíveis: False ou True
save_log_to_file: True

# [en_US] Option for use multiples accounts on same monitor
# Default value: False
#
# [pt_BR] Opção para usar multiplas contas no mesmo monitor
# Valor padrão: False
multiples_accounts_same_monitor:
  enable: True
  window_contains_title: "Bombcrypto -"

# [en_US] If you have macbook or laptop with Retina screen, enable this feature
# Default value: False
#
# [pt_BR] Se você tem um macbook ou notebook com tela retina, habilite essa função
# Valor padrão: False
is_retina_screen: False

# [en_US] Speed of mouse move for automation
# Default value: 1
#
# [pt_BR] Velocidade do movimento do mouse para a automação
# Valor padrão: 1
mouse_move_speed: 0.6

scale_image:
  # [en_US] Enable for use different scale on your browser
  # Default value: False
  #
  # [pt_BR] Habilita para usar uma escala diferente de visão em seu navegador
  # Valor padrão: False
  enable: False

  # [en_US] When enable scale, set what scale value used on your browser
  # Default value: 100
  #
  # [pt_BR] Quando a escala está habilitada, especificar o valor de escala utilizada em seu navegador
  # Valor padrão: 100
  percent: 100

  # [en_US] When enable scale, set what scale images threshold to compare images
  # Default value: 0.9
  #
  # [pt_BR] Quando a escala está habilitada, especificar o valor de threshold para comparação de imagens
  # Valor padrão: 0.9
  threshold: 0.9

debug:
  # When home feature enable
  sendHeroesHome: False

  # When select_heroes_mode == 'all'
  clickButtons: False

  # When select_heroes_mode == 'all' and HOME feature is Disabled
  clickWorkAllButton: False

  # When select_heroes_mode == 'green'
  clickGreenBarButtons: False

  # When select_heroes_mode == 'full'
  clickFullBarButtons: False

  #####
  # When call clickBtn function
  clickBtn: False

  # When use scroll function
  scroll: False



space:
  general_settings:
    #Selecione a resulução, disponiveis:
    #1 - 1366x768
    #2 - 1680x1050
    #3 - 1920x1080
    resolution: 1

  # Valores de configuração do bot
  ship_settings:
    # Quantidade total de naves (total)
    empty_qtd_spaceships: 17
    
    # Quantas naves deseja entrar para o boss
    qtd_send_spaceships: 15

    # Se deseja dar surrender, alterar para o valor do boss (zero não faz)
    boss_surrender: 8
    
    # Envia somente naves 100% (True/False)
    send_ships_full: True

    # Reparar Naves (True/False)
    repair_ships: True

    # Se desejar que remova as naves antes de adicionar outras (True/False)
    remove_ships: True 

    # Volta para a spaceship nas waves 9, 14 e 19
    key_waves: False

    # Volta nas seleções de naves sempre que finalizar o surrender
    select_spaceship_after_surrender: True

    # Envia somente naves comuns para batalha 
    send_only_common: False # Ainda em desenvolvimento

    # Captura as recomenças de cada boss (valor medio e multicador)
    get_rewards: True

    # Timeout para dar refresh na tela caso nenhuma ação tenha sido encontrada. Valor padrão 360 (6min)
    refresh_page: 360

  optimization_settings:    
    # Tempo entre clicks (se conexão ruim aumentar esse valor) Valor padrão: 0.6
    time_click: 0.6

    # Velocidade de locomoção do mouse (padrão 0.1)
    move_speed_mouse: 0.1
    
    # Deixar o filtro max-ammo sempre ativo
    set_filter_max_ammo: True

  # Valor de confiança das comparações
  threshold:
    # Valor padrão: 0.7
    default: 0.7

    # Valor padrão: 0.8
    commom: 0.8
    
    # Valor padrão 0.9
    hard: 0.9

    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # Valor padrão: 0.92
    go-fight: 0.92

    # Valor padrão: 0.95
    green_bar: 0.95

    # Valor padrão 0.98
    15-15-ships: 0.98

    # Valor padrão 0.98
    0-15: 0.98

    # Valor padrão 0.8
    confirm-end-boss: 0.8

    # Ships rarity. Valor padrão 0.92
    ships_rarity: 0.92

    # Rewards 
    rewards: 0.9
# Media de valor de recompensa MEDIA para cada boss. Base retirada dia 21.02.22 (podendo sofrer alterações)
  rewards:
    boss_1: 0.09
    boss_2: 0.11
    boss_3: 0.13
    boss_4: 0.19
    boss_5: 0.18
    boss_6: 0.13
    boss_7: 0.20
    boss_8: 0.27
    boss_9: 0.35
    boss_10: 0.66
    boss_11: 0.50
    boss_12: 0.60
    boss_13: 0.66
    boss_14: 0.72
    boss_15: 1.08
    boss_16: 0.95
    boss_17: 0.96
    boss_18: 1.14
    boss_19: 1.04
    boss_20: 1.95